// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectEstimationTool.Models;

public partial class DefaultFunctionalArea
{
    public int FunctionalAreaid { get; set; }

    public string FunctionalAreaName { get; set; }
}