// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectEstimationTool.Models;

public partial class DefaultSoftware
{
    public int SoftwareId { get; set; }

    public string SoftwareName { get; set; }

    public int MonthlyRate { get; set; }
}