// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ProjectEstimationTool.Models;

public partial class Summary
{
    public int SummaryId { get; set; }

    public int ProjectId { get; set; }

    public double TravelBudget { get; set; }

    public double Contingency { get; set; }

    public double Total { get; set; }

    public virtual Project Project { get; set; }
}